_target_: codis.lightning.modules.ContrastiveClassifier
train_iters_per_epoch: ${eval:'${dataset.shapes_per_task} * ${dataset.factor_resolution}**4 / ${dataset.batch_size}'}
backbone: resnet18
optimizer: adam
out_dim: 128
schedule_lr: true
warmup_epochs: 10
lr: ${training.lr}
weight_decay: 1e-6
loss_temperature: 0.5
shapes_per_task: ${dataset.shapes_per_task}