_target_: codis.lightning.modules.ContrastiveClassifier
backbone: resnet18
warmup_epochs: 10
lr: ${training.lr}
opt_weight_decay: 1e-6
loss_temperature: 0.5
shapes_per_task: ${dataset.shapes_per_task}