_target_: codis.lightning.modules.SpatialTransformer
img_size: ${dataset.img_size}
in_channels: ${dataset.num_channels}
encoder: simple_cnn
channels: [16, 32, 64, 64, 128]
gamma: 0.5
lr: ${training.lr}
factors_to_regress: [orientation, scale, position_x, position_y]