_target_: codis.lightning.modules.SpatialTransformer
img_size: ${dataset.img_size}
in_channels: ${dataset.num_channels}
encoder: resnet18
channels: [16, 32, 64, 64, 128]
gamma: 1.0
lr: ${training.lr}
factors_to_regress: [orientation, scale, position_x, position_y]
buffer_chunk_size: 48