name: idsprites
batch_size: 512
factor_resolution: 16
img_size: 224
num_channels: 3
num_workers: 8
shapes_per_task: 1
tasks: 16
train_split: 0.98
val_split: 0.01
test_split: 0.01
test_dataset_size: 100000