name: idsprites
path: ${oc.env:WORK}/datasets/idsprites
batch_size: 256
factor_resolution: 8
img_size: 256
num_channels: 3
num_workers: 8
shapes_per_task: 10
accumulate_test_set: true
test_subset: 100
tasks: 1000