name: idsprites
path: $WORK/datasets/idsprites_sample
batch_size: 256
factor_resolution: 8
img_size: 256
num_channels: 3
num_workers: 8
shapes_per_task: 10
train_dataset_size: 100000
val_dataset_size: 10000
test_dataset_size: 10000