_target_: avalanche.training.supervised.CoPE
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.lr}
criterion:
  _target_: torch.nn.CrossEntropyLoss
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}
n_classes: ${eval:'${dataset.tasks} * ${dataset.shapes_per_task}'}
mem_size: 200