_target_: avalanche.training.supervised.EWC
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.lr}
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}