_target_: avalanche.training.supervised.LearningToPrompt
model_name: vit_tiny_patch16_224
criterion:
  _target_: torch.nn.CrossEntropyLoss
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}
num_classes: ${eval:'${dataset.tasks} * ${dataset.shapes_per_task}'}