_target_: avalanche.training.supervised.Naive
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.lr}
plugins:
  - _target_: avalanche.training.plugins.ReplayPlugin
    mem_size: buffer.mem_size
    storage_policy:
      _target_: avalanche.training.storage_policy.ReservoirSamplingBuffer
      max_size: buffer.mem_size
criterion:
  _target_: torch.nn.CrossEntropyLoss
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}