_target_: avalanche.training.supervised.Replay
optimizer:
  _target_: torch.optim.Adam
  lr: ${training.lr}
criterion:
  _target_: torch.nn.CrossEntropyLoss
storage_policy:
  _target_: avalanche.training.storage_policy.ReservoirSamplingBuffer
  max_size: ${mem_size}
train_mb_size: ${dataset.batch_size}
eval_mb_size: ${dataset.batch_size}
train_epochs: ${trainer.max_epochs}
mem_size: 200