defaults:
  - _self_
  - dataset: idsprites
  - model: regressor
  - strategy: naive

project:
  name: disco

output_dir: ${oc.env:WORK}/${project.name}

hydra:
  run:
    dir: ${output_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

training:
  strategy: naive
  reset_model: false
  callbacks: [logging, metrics, timer]
  lr: 0.001
  test_once: false
  test_every_n_tasks: 1
  checkpoint_every_n_tasks: 10
  epochs_per_task: 5
  validate: true
  log_train_accuracy: false
  log_val_accuracy: false
  log_test_accuracy: true
  sanity_check: false

buffer:
  mem_size: 200

trainer:
  _target_: lightning.Trainer
  default_root_dir: ${output_dir}/lightning
  enable_checkpointing: false
  enable_progress_bar: false
  max_epochs: ${training.epochs_per_task}
  log_every_n_steps: 1
  logger: ${wandb}
  strategy: auto
  accumulate_grad_batches: 1
#  accelerator: auto  # "cpu", "gpu", "tpu", "ipu", "hpu", "mps", "auto"
#  devices: -1
  num_nodes: 1
  precision: 32
  profiler: null

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  save_dir: ${output_dir}/wandb
  project: ${project.name}
  group: null
  mode: online
  notes: null
  name: null