defaults:
 - _self_
 - dataset: idsprites
 - model: stn
 - strategy: naive

project:
  name: codis

hydra:
  run:
    dir: ${oc.env:WORK}/${project.name}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

training:
  mode: continual
  callbacks: [logging, visualization, checkpointing]
  lr: 0.001
  test_once: false
  test_every_n_tasks: 10

trainer:
  _target_: lightning.pytorch.Trainer
  default_root_dir: ${oc.env:WORK}/${project.name}/lightning
  enable_checkpointing: true
  enable_progress_bar: false
  max_epochs: 5
  log_every_n_steps: 1
  logger: ${wandb}
  strategy: auto

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  save_dir: ${oc.env:WORK}/${project.name}/wandb
  project: ${project.name}
  group: null
  mode: online
  notes: null
  name: null