name: Linting and formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pylint pytest
        python -m pip install -r requirements.txt --upgrade
        python -m pip install -e .
    - name: Lint with pylint
      run: |
        pylint ./codis --rcfile .pylintrc
    - name: Run black
      run: black --check --verbose ./codis